Feature: display component definitions as grid
ditrit/leto-modelizer pull request #117
Opened 2022-12-01 11:31 UTC by Rahzbob

2022-12-01 13:59 UTC, k-y0u requested changes

2022-12-01 13:59 UTC, k-y0u commented on src/components/card/ComponentDefinitionCard.vue
> +        <q-item-label class="component-definition-type">{{ definition.type }}</q-item-label>
to divide in 3 lines.

2022-12-01 13:59 UTC, k-y0u commented on changelog.md
> +<<<<<<< HEAD
rebase failed

2022-12-01 14:52 UTC, Rahzbob commented on src/components/card/ComponentDefinitionCard.vue
> +        <q-item-label class="component-definition-type">{{ definition.type }}</q-item-label>
done

2022-12-01 14:58 UTC, k-y0u submitted a review, later dismissed

2022-12-01 15:09 UTC, justinehell approved these changes

2022-12-16 09:11 UTC, Zorin95670 approved these changes

2022-12-16 14:28 UTC, justinehell submitted a review, later dismissed

2022-12-16 15:12 UTC, Zorin95670 requested changes

2022-12-16 15:51 UTC, k-y0u approved these changes

2022-12-16 15:52 UTC, justinehell approved these changes

2022-12-16 15:53 UTC, Zorin95670 approved these changes

2022-12-16 15:53 UTC, merged