Bugfix/create file path
ditrit/leto-modelizer pull request #118
Opened 2022-12-01 15:47 UTC by justinehell

When creating a file, wrong path was used to open corresponding file tab
Update `CreateFileEvent` by adding new `path` param
Update all functions that called this event
 - `onCreateFileEvent` function in `ModelizerTextView.vue`
 - `onSubmit` function in `CreateFileForm.vue`
 -  `createProjectFolder` function in `Project.js`

2022-12-01 16:06 UTC, k-y0u requested changes

2022-12-01 16:06 UTC, k-y0u commented on src/composables/events/FileEvent.js
> + * The event should be an Object that contains the `name`, `path` of the file and `isFolder`.
you can remove `of the file`

2022-12-01 16:06 UTC, k-y0u commented on src/components/form/CreateFileForm.vue
> +  const filePathOrFileInput = props.isFolder ? `${parent}${fileName.value}` : new FileInput({
weird

2022-12-01 16:45 UTC, justinehell commented on src/components/form/CreateFileForm.vue
> +  const filePathOrFileInput = props.isFolder ? `${parent}${fileName.value}` : new FileInput({
agreed, changed

2022-12-01 16:53 UTC, justinehell commented on src/composables/events/FileEvent.js
> + * The event should be an Object that contains the `name`, `path` of the file and `isFolder`.
done

2022-12-02 08:48 UTC, k-y0u commented on tests/unit/components/ModelizerTextView.spec.js
> -      wrapper.vm.activeFileTab = { isSelected: false, id: 'fileName' };
I'm not sure if this part should be remove.

2022-12-02 09:09 UTC, k-y0u approved these changes

2022-12-02 10:30 UTC, Zorin95670 approved these changes

2022-12-02 10:32 UTC, k-y0u approved these changes

2022-12-02 10:38 UTC, merged