Library: Update plugin-core to version 0.11.0
ditrit/leto-modelizer pull request #151
Opened 2023-01-13 15:29 UTC by Zorin95670

2023-01-16 14:50 UTC, k-y0u requested changes

2023-01-16 14:50 UTC, k-y0u commented on src/components/ModelizerModelView.vue
> +  fileInputs.forEach((file) => {
Should not be done here. Better be in Project.js/readProjectFile.

2023-01-16 14:50 UTC, k-y0u commented on src/composables/Project.js
> +      file.content || '',
when do you encounter the case where content is null/undefined ?

2023-01-16 15:23 UTC, Zorin95670 commented on src/composables/events/PluginEvent.js
> + * Represent a rxjs Event object to emit and to receive events when plugin have updated the
done

2023-01-16 15:24 UTC, justinehell requested changes

2023-01-16 15:24 UTC, justinehell commented on src/composables/PluginManager.js
> +    UpdateEvent: PluginEvent.UpdateEvent,
why delete EditEvent ?

2023-01-16 15:46 UTC, k-y0u approved these changes

2023-01-16 15:48 UTC, justinehell submitted a review, later dismissed

2023-01-18 10:08 UTC, k-y0u approved these changes

2023-01-18 10:27 UTC, merged