Feature : create component from template
ditrit/leto-modelizer pull request #157
Opened 2023-01-27 11:36 UTC by justinehell

Close https://github.com/ditrit/leto-modelizer/issues/150

2023-02-01 11:21 UTC, Zorin95670 requested changes

2023-02-01 13:06 UTC, justinehell commented on tests/unit/composables/Project.spec.js
> +    it('should succed and return undefined', async () => {
done

2023-02-01 13:17 UTC, justinehell commented on src/components/card/ComponentDefinitionCard.vue
> +            :title="definition.title"
done

2023-02-01 15:32 UTC, justinehell commented on src/components/ModelizerModelView.vue
> +async function getComponentTemplates() {
done

2023-02-01 15:32 UTC, justinehell commented on src/composables/TemplateManager.js
> +  return templates
done

2023-02-06 14:06 UTC, Zorin95670 requested changes

2023-02-06 14:06 UTC, Zorin95670 commented on src/components/drawer/ComponentDefinitionsDrawer.vue
> +              :definitions="templates"
one line

2023-02-06 14:06 UTC, Zorin95670 commented on README.md
> +      proxy_pass process.env.TEMPLATE_LIBRARY_BASE_URL;
proxy pass TEMPLATE_LIBRARY_BASE_URL;

2023-02-06 14:43 UTC, justinehell commented on src/components/drawer/ComponentDefinitionsDrawer.vue
> +              :definitions="templates"
done

2023-02-06 14:44 UTC, justinehell commented on README.md
> +      proxy_pass process.env.TEMPLATE_LIBRARY_BASE_URL;
done

2023-02-06 15:09 UTC, k-y0u requested changes

2023-02-06 15:10 UTC, justinehell commented on src/composables/Project.js
> + * @param {FileInput} file - File input.
done

2023-02-06 15:16 UTC, justinehell commented on tests/unit/components/ModelizerModelView.spec.js
> +  describe('Test functions', () => {
done

2023-02-06 15:18 UTC, justinehell commented on tests/unit/composables/Project.spec.js
> +      const error = await appendProjectFile('projectId', { path: 'error', content: 'content' }).catch((e) => e);
keep it

2023-02-06 15:21 UTC, justinehell commented on tests/unit/composables/PluginManager.spec.js
> +    it('should update plugin.components and call draw() function', async () => {
done

2023-02-06 15:22 UTC, justinehell commented on src/composables/TemplateManager.js
> +  return [];
done

2023-02-06 15:24 UTC, justinehell commented on src/components/ModelizerModelView.vue
> +  await getTemplatesByType('component', data.plugins[0]?.data?.name)
done

2023-02-06 15:25 UTC, justinehell commented on src/components/card/ComponentDefinitionCard.vue
> + * On template definition click, get all related remote files and append them to fs.
done

2023-02-06 15:25 UTC, justinehell commented on tests/unit/composables/TemplateManager.spec.js
> +    it('should return remote file content', async () => {
done

2023-02-06 16:18 UTC, k-y0u approved these changes

2023-02-06 16:19 UTC, Zorin95670 approved these changes

2023-02-06 16:19 UTC, merged