Feature/add models page
ditrit/leto-modelizer pull request #162
Opened 2023-02-01 13:52 UTC by k-y0u

Add new view to display model list of the project.
Update inner navigation accordingly.

2023-02-10 14:19 UTC, justinehell requested changes

2023-02-12 11:14 UTC, k-y0u commented on src/components/form/RenameModelForm.vue
> + * Emit a positive notification on success and emit a UpdateModel event.
done

2023-02-13 10:56 UTC, Zorin95670 approved these changes

2023-02-13 10:57 UTC, justinehell approved these changes

2023-02-13 12:11 UTC, merged