Improvement: use terraform for e2e tests
ditrit/leto-modelizer pull request #169
Opened 2023-02-08 12:52 UTC by Rahzbob

2023-02-27 15:13 UTC, k-y0u requested changes

2023-02-27 15:42 UTC, justinehell commented on cypress/e2e/ModelizerPage/SwitchView/add.component.feature
> +  Scenario: Link two components (Model view) should update plugin file's content with new attributes properties (Text view)
done

2023-02-28 08:52 UTC, k-y0u approved these changes

2023-02-28 09:55 UTC, Zorin95670 approved these changes

2023-02-28 09:55 UTC, merged