Feature : About page
ditrit/leto-modelizer pull request #194
Opened 2023-02-20 17:17 UTC by justinehell

Add About page

2023-02-22 10:45 UTC, k-y0u requested changes

2023-02-22 10:45 UTC, k-y0u commented on src/i18n/en-US/index.js
> +        description: 'It is a low code modelizer that works with external plugins for technology integration (terraform, jenkins, kubernetes...). The goal of Leto Modelizer is to become the standard
`technology integration` -> `integration technology` ?

2023-02-22 10:45 UTC, k-y0u commented on src/pages/AboutPage.vue
> +    class=""
no class in `class`

2023-02-22 10:45 UTC, k-y0u commented on src/layouts/MainLayout.vue
> +  <q-layout view="lHh Lpr lff">
ATTENTION ! This could change the structure of other pages

2023-02-22 10:45 UTC, k-y0u commented on src/layouts/MainLayout.vue
> +    <q-footer
not agree (let's talk about it)

2023-02-22 10:52 UTC, justinehell commented on src/i18n/en-US/index.js
> +        description: 'It is a low code modelizer that works with external plugins for technology integration (terraform, jenkins, kubernetes...). The goal of Leto Modelizer is to become the standard
done

2023-02-22 10:52 UTC, justinehell commented on src/pages/AboutPage.vue
> +    class=""
oops done

2023-02-22 10:59 UTC, k-y0u commented on changelog.md
> +* Create About page and footer
missing dot

2023-02-22 11:08 UTC, k-y0u approved these changes

2023-02-27 14:06 UTC, k-y0u submitted a review, later dismissed

2023-02-27 15:58 UTC, k-y0u approved these changes

2023-02-27 15:58 UTC, Zorin95670 approved these changes

2023-02-27 15:59 UTC, merged