Feature : Rename project
ditrit/leto-modelizer pull request #197
Opened 2023-02-24 14:24 UTC by justinehell

2023-02-27 14:31 UTC, k-y0u submitted a review, later dismissed

2023-03-01 14:05 UTC, k-y0u requested changes

2023-03-01 14:05 UTC, k-y0u commented on src/components/dialog/NewProjectDialog.vue
> +  await initProject(project);
no error management

2023-03-06 12:14 UTC, justinehell commented on tests/unit/composables/QuasarFieldRule.spec.js
> +    it('should return true without duplicated project', () => {
done

2023-03-06 12:14 UTC, justinehell commented on tests/unit/composables/QuasarFieldRule.spec.js
> +    it('should return string error message with duplicated project', () => {
done

2023-03-06 13:29 UTC, justinehell commented on src/components/dialog/NewProjectDialog.vue
> +  await initProject(project);
done

2023-03-06 13:29 UTC, justinehell commented on src/components/form/NewProjectForm.vue
> +  Notify.create({
moved inside NewProjectDialog

2023-03-06 14:14 UTC, k-y0u submitted a review, later dismissed

2023-03-06 16:04 UTC, Zorin95670 approved these changes

2023-03-06 16:11 UTC, k-y0u approved these changes

2023-03-06 16:28 UTC, Zorin95670 approved these changes

2023-03-06 16:28 UTC, merged