Improvement/update modelizer page management
ditrit/leto-modelizer pull request #200
Opened 2023-03-03 09:44 UTC by k-y0u

2023-03-06 09:46 UTC, Zorin95670 commented on src/pages/ModelizerPage.vue
> +          v-if="viewType === 'text'"
v-else-if

2023-03-07 15:32 UTC, k-y0u commented on src/pages/ModelizerPage.vue
> +          v-if="viewType === 'text'"
done

2023-03-15 12:59 UTC, justinehell requested changes

2023-03-21 10:07 UTC, k-y0u commented on src/components/ModelizerTextView.vue
> +async function onSelectFileTab(event) {
done

2023-03-21 10:07 UTC, k-y0u commented on src/pages/ModelsPage.vue
> +.q-layout.modelizer-page>.q-page-container {
done

2023-03-23 15:41 UTC, Zorin95670 commented on cypress/e2e/ModelizerPage/ModelView/plugin/filter.plugin.feature
> +    Then I expect '[data-cy="component-defnitions-item_terrator-plugin"] [class*="component-definition-card"]' appear 18 times on screen
And

2023-03-23 16:20 UTC, justinehell requested changes

2023-03-23 16:20 UTC, justinehell commented on cypress/e2e/ModelizerPage/SwitchView/delete.feature
>  # TODO: update/fix test
remove if fixed

2023-03-23 16:20 UTC, justinehell commented on cypress/e2e/ModelizerPage/TextView/file/add.file.feature
>      And  I wait 2 seconds
2 seconds

2023-03-23 16:20 UTC, justinehell commented on cypress/e2e/ModelizerPage/TextView/file/create.file.feature
>      And  I wait 2 seconds
2 seconds

2023-03-23 16:20 UTC, justinehell commented on cypress/e2e/ModelizerPage/TextView/file/open.file.feature
>      And  I wait 2 seconds
2 seconds

2023-03-23 16:20 UTC, justinehell commented on cypress/e2e/ModelizerPage/TextView/file/open.file.feature
> +    Then   I expect '[data-cy="file-explorer"] [data-cy="file_README.md"]' exists
remove 1 space after `When` and |Then`

2023-03-23 16:20 UTC, justinehell commented on cypress/e2e/RoundTrips/create.project.template.files.feature
> +    Then I expect '[data-cy="file-explorer"] [data-cy="file_terrator-plugin/infra1/provider.tf"]' exists
Then -> And

2023-03-23 16:20 UTC, justinehell commented on cypress/e2e/RoundTrips/delete.project.feature
> +    Then I expect '[data-cy="file-explorer"] [data-cy="folder_{{ projectName }}"]' exists
Then -> And

2023-03-23 16:20 UTC, justinehell commented on cypress/e2e/RoundTrips/rename.project.feature
>      And  I expect '[data-cy="file-explorer"] [data-cy="folder_terrator-plugin/{{modelName}}"]' exists
And -> Then

2023-03-23 16:20 UTC, justinehell commented on cypress/e2e/roundtrip.feature
>    # TODO: update/fix test
remove if fixed

2023-03-24 10:08 UTC, k-y0u commented on cypress/e2e/ModelizerPage/Common/switch.view.feature
> +    Then I expect current url is 'projectName/modelizer/draw\?path=terrator-plugin/modelName'
Done

2023-03-24 10:08 UTC, k-y0u commented on cypress/e2e/ModelizerPage/ModelView/plugin/filter.plugin.feature
> +    Then I expect '[data-cy="component-defnitions-item_terrator-plugin"] [class*="component-definition-card"]' appear 18 times on screen
Done

2023-03-24 10:15 UTC, k-y0u commented on src/components/ModelizerNavigationBar.vue
>   */
done

2023-03-24 10:20 UTC, k-y0u commented on cypress/e2e/ModelizerPage/Common/switch.view.feature
>    # TODO: update/fix test
done

2023-03-24 10:20 UTC, k-y0u commented on cypress/e2e/ModelizerPage/Common/switch.view.feature
>    # TODO: update/fix test
done

2023-03-24 10:20 UTC, k-y0u commented on cypress/e2e/ModelizerPage/ModelView/plugin/display.component.feature
>  # TODO: update/fix test
done

2023-03-24 10:20 UTC, k-y0u commented on cypress/e2e/ModelizerPage/ModelView/plugin/filter.plugin.feature
>  # TODO: update/fix test
done

2023-03-24 10:21 UTC, k-y0u commented on cypress/e2e/ModelizerPage/ModelView/plugin/init.plugin.feature
>  # TODO: update/fix test
done

2023-03-24 10:21 UTC, k-y0u commented on cypress/e2e/ModelizerPage/SwitchView/add.component.feature
>  # TODO: update/fix test
done

2023-03-24 10:22 UTC, k-y0u commented on cypress/e2e/roundtrip.feature
>    # TODO: update/fix test
done

2023-03-24 10:27 UTC, k-y0u commented on cypress/e2e/ModelizerPage/ModelView/plugin/filter.plugin.feature
> +    Then I expect '[data-cy="component-defnitions-item_terrator-plugin"] [class*="component-definition-card"]' appear 2 time on screen
done

2023-03-24 10:27 UTC, k-y0u commented on cypress/e2e/ModelizerPage/SwitchView/add.component.feature
> +    Then I expect '[data-cy="file_terrator-plugin/modelName/new_file.tf"]' appear 1 times on screen
done

2023-03-24 10:28 UTC, k-y0u commented on cypress/e2e/ModelizerPage/SwitchView/add.component.feature
> +    Then I expect '[data-cy="file_terrator-plugin/modelName/new_file.tf"]' appear 1 times on screen
done

2023-03-24 10:28 UTC, k-y0u commented on cypress/e2e/ModelizerPage/SwitchView/add.component.feature
> +    And  I expect '[data-cy="file_terrator-plugin/modelName/leto-modelizer.config.json"]' appear 1 times on screen
done

2023-03-24 10:28 UTC, k-y0u commented on cypress/e2e/ModelizerPage/SwitchView/add.component.feature
> +    Then I expect '[data-cy="file_terrator-plugin/modelName/new_file.tf"]' appear 1 times on screen
done

2023-03-24 10:28 UTC, k-y0u commented on cypress/e2e/ModelizerPage/SwitchView/add.component.feature
> +    And  I expect '[data-cy="file_terrator-plugin/modelName/leto-modelizer.config.json"]' appear 1 times on screen
done

2023-03-24 10:28 UTC, k-y0u commented on cypress/e2e/ModelizerPage/SwitchView/add.component.feature
> +    And  I expect '[data-cy="file_terrator-plugin/modelName/leto-modelizer.config.json"]' appear 1 times on screen
done

2023-03-24 10:28 UTC, k-y0u commented on cypress/e2e/ModelizerPage/SwitchView/delete.feature
>  # TODO: update/fix test
done

2023-03-24 10:29 UTC, k-y0u commented on cypress/e2e/ModelsPage/delete.model.feature
> +    And  I wait 1 seconds
done

2023-03-24 10:36 UTC, k-y0u commented on cypress/e2e/ModelsPage/create.model.feature
> +    Then I expect current url is '{{projectName}}/models'
When I had to update the url, I did it.
Good or bad, when can discuss it ?
I can make a global change in a new commit.
I can also reverse this change on my actual commit.
@Zorin95670 What do you think about it ?

2023-03-24 10:45 UTC, k-y0u commented on cypress/e2e/ModelizerPage/ModelView/plugin/filter.plugin.feature
> +  Scenario Outline: Set text as '<filter>'should display only one element
done

2023-03-24 10:45 UTC, k-y0u commented on cypress/e2e/ModelsPage/create.template.feature
>      And  I expect '[data-cy="file-explorer"] [data-cy="file_terrator-plugin/{{modelName}}/main.tf"]' exists
done

2023-03-24 10:46 UTC, k-y0u commented on cypress/e2e/RoundTrips/create.project.template.files.feature
> +    Then I expect '[data-cy="file-explorer"] [data-cy="file_terrator-plugin/infra1/provider.tf"]' exists
done

2023-03-24 10:46 UTC, k-y0u commented on cypress/e2e/RoundTrips/delete.project.feature
> +    Then I expect '[data-cy="file-explorer"] [data-cy="folder_{{ projectName }}"]' exists
done

2023-03-24 10:46 UTC, k-y0u commented on cypress/e2e/RoundTrips/rename.project.feature
>      And  I expect '[data-cy="file-explorer"] [data-cy="folder_terrator-plugin/{{modelName}}"]' exists
done

2023-03-24 13:37 UTC, Zorin95670 approved these changes

2023-03-24 14:23 UTC, merged