Improvement: e2e for models page
ditrit/leto-modelizer pull request #204
Opened 2023-03-08 12:59 UTC by Zorin95670

2023-03-08 16:14 UTC, k-y0u requested changes

2023-03-08 16:14 UTC, k-y0u commented on src/composables/QuasarFieldRule.js
> +export function isUniqueModelName(t, models, plugin, value) {
not only the name

2023-03-08 16:14 UTC, k-y0u commented on tests/unit/components/ModelizerModelsView.spec.js
> -    Project.getAllModels.mockImplementation((path) => {
'Project' is defined but never used

2023-03-08 16:14 UTC, k-y0u commented on tests/unit/composables/Project.spec.js
> +  renameProject, getModelsBasePath,
divide line

2023-03-08 16:14 UTC, k-y0u commented on tests/unit/composables/QuasarFieldRule.spec.js
> +  isUniqueProjectName, isUniqueModelName,
divide line

2023-03-17 13:05 UTC, Zorin95670 commented on cypress/support/step_definitions/html.js
> +    expect(text.trim().indexOf(fileContent) >= 0).to.eq(true);
done

2023-03-17 13:06 UTC, Zorin95670 commented on cypress/support/step_definitions/html.js
> +    return cy.get('[data-cy="monaco-editor"] .view-lines .view-line');
done

2023-03-17 13:11 UTC, Zorin95670 commented on cypress/support/step_definitions/html.js
> +    for (let index = 0; index < lines.length; index += 1) {
no, because lines is not an `Array` it's `JQuery<E>`

2023-03-17 13:13 UTC, Zorin95670 commented on src/components/ModelizerModelsView.vue
> +          data-cy="create-model"
done

2023-03-17 13:14 UTC, Zorin95670 commented on src/components/drawer/ComponentDefinitionsDrawer.vue
> +          data-cy="models-link"
done

2023-03-17 13:15 UTC, Zorin95670 commented on src/components/form/CreateModelForm.vue
> +        data-cy="create-model-form-submit"
done

2023-03-17 13:15 UTC, Zorin95670 commented on src/components/form/ImportModelTemplateForm.vue
> +        data-cy="import-model-template-form-submit"
done

2023-03-17 13:17 UTC, Zorin95670 commented on cypress/e2e/ModelsPage/create.model.feature
> +  Scenario: Create model and try to create model without name should be not possible
done

2023-03-17 13:17 UTC, Zorin95670 commented on cypress/e2e/ModelsPage/create.model.feature
> +  Scenario: Create model and try to create same model should be not possible
done

2023-03-17 13:17 UTC, Zorin95670 commented on cypress/e2e/ModelsPage/create.template.feature
> +Feature: Test models page: model creation
done

2023-03-17 13:18 UTC, Zorin95670 commented on cypress/e2e/ModelsPage/create.template.feature
> +Feature: Test models page: model creation
done

2023-03-17 13:19 UTC, Zorin95670 commented on cypress/e2e/ModelsPage/create.template.feature
> +  Scenario: Create model and try to create same template model should be not possible
done

2023-03-17 13:19 UTC, Zorin95670 commented on cypress/e2e/ModelsPage/create.template.feature
> +  Scenario: Create template model and try to create model without name should be not possible
done

2023-03-17 13:20 UTC, Zorin95670 commented on cypress/e2e/ModelsPage/delete.model.feature
> +Feature: Test models page: model creation
done

2023-03-17 13:20 UTC, Zorin95670 commented on cypress/e2e/ModelsPage/rename.model.feature
> +Feature: Test models page: model creation
done

2023-03-17 13:22 UTC, Zorin95670 commented on cypress/e2e/ModelsPage/rename.model.feature
> +  Scenario: Create model and rename it and verify the new name
done

2023-03-17 13:24 UTC, Zorin95670 commented on src/composables/QuasarFieldRule.js
> +export function isUniqueModelName(t, models, plugin, value) {
done

2023-03-17 13:26 UTC, Zorin95670 commented on src/components/form/ImportModelTemplateForm.vue
> +  appendProjectFile, getAllModels,
dones

2023-03-17 13:26 UTC, Zorin95670 commented on src/composables/QuasarFieldRule.js
> + * @param {Array} models - List of models names.
done

2023-03-17 13:27 UTC, Zorin95670 commented on tests/unit/components/ModelizerModelsView.spec.js
> -    Project.getAllModels.mockImplementation((path) => {
done

2023-03-17 13:27 UTC, Zorin95670 commented on tests/unit/composables/Project.spec.js
> +  renameProject, getModelsBasePath,
done

2023-03-17 13:28 UTC, Zorin95670 commented on tests/unit/composables/QuasarFieldRule.spec.js
> +  isUniqueProjectName, isUniqueModelName,
done

2023-03-17 13:28 UTC, Zorin95670 commented on nginx.conf
> +
done

2023-03-17 13:36 UTC, Zorin95670 commented on cypress/e2e/ModelsPage/create.model.feature
> +  Scenario: Create two models and verify redirection
done

2023-03-17 13:37 UTC, Zorin95670 commented on cypress/e2e/ModelsPage/delete.model.feature
> +  Scenario: Create model, delete it, create another model, check previous model files are deleted and recreate the first model
done

2023-03-17 14:21 UTC, k-y0u commented on cypress/e2e/ModelsPage/delete.model.feature
> +  Scenario: Create model, delete it, create another model, check previous model files are deleted and recreate the first model
nope

2023-03-17 14:23 UTC, k-y0u commented on cypress/e2e/ModelsPage/rename.model.feature
> +  Scenario: Create model and rename it and verify the new name
nope

2023-03-17 14:59 UTC, justinehell requested changes

2023-03-17 14:59 UTC, justinehell commented on cypress/e2e/ModelsPage/create.model.feature
> +    And I set context field "modelName" with "modelTest"
add space between `And` and `I` to align with` in `Given I ...`

2023-03-17 14:59 UTC, justinehell commented on cypress/e2e/ModelsPage/create.model.feature
> +    Then I expect current url is "http://localhost:8080/#/modelizer/{{projectName}}/models"
Why not just `#/modelizer/...` ? like in other files

2023-03-17 14:59 UTC, justinehell commented on src/components/form/CreateModelForm.vue
> +      data-cy="plugin-select"
put this last

2023-03-17 15:25 UTC, k-y0u commented on cypress/e2e/ModelsPage/rename.model.feature
> +    And  I expect '[data-cy="file-explorer"] [data-cy="folder_terrator-plugin/{{modelName}}"]' exists
then

2023-03-17 15:56 UTC, justinehell approved these changes

2023-03-17 16:16 UTC, justinehell submitted a review, later dismissed

2023-03-17 16:18 UTC, k-y0u approved these changes

2023-03-17 16:42 UTC, merged