Improvement : updating data-cy for e2e tests
ditrit/leto-modelizer pull request #206
Opened 2023-03-10 16:32 UTC by justinehell

- Updating and standardization `data-cy` for e2e tests

2023-03-14 10:27 UTC, Zorin95670 commented on src/components/ModelizerModelView.vue
> +          data-cy="draw-root"
draw-area

2023-03-14 14:44 UTC, justinehell commented on src/components/ModelizerModelView.vue
> +          data-cy="draw-root"
done

2023-03-15 09:09 UTC, Zorin95670 commented on src/components/menu/FileExplorerActionMenu.vue
> +          data-cy="create-folder"
-action

2023-03-15 14:47 UTC, k-y0u requested changes

2023-03-15 14:47 UTC, k-y0u commented on src/components/inputs/ObjectInput.vue
> +          data-cy="object-attributes-error"
no need to add it if not used

2023-03-15 14:47 UTC, k-y0u commented on src/components/inputs/ObjectInput.vue
> +      data-cy="object-attributes-list"
no need to add it if not used

2023-03-15 14:47 UTC, k-y0u commented on src/components/drawer/ComponentDefinitionsDrawer.vue
> +        data-cy="filter-plugin-definitions-input"
`definitions-filter-input`

2023-03-15 14:47 UTC, k-y0u commented on src/components/drawer/ComponentDefinitionsDrawer.vue
> +          :data-cy="`plugin-definitions_${plugin.data.name}`"
`component-defnitions-item`

2023-03-15 14:47 UTC, k-y0u commented on src/components/drawer/ComponentDefinitionsDrawer.vue
>            data-cy="`template-definitions"
`template-definitions-item`

2023-03-15 14:47 UTC, k-y0u commented on src/components/drawer/ComponentDetailPanel.vue
> +                data-cy="selected-component-input"
no need ?

2023-03-15 14:47 UTC, k-y0u commented on src/components/drawer/ComponentDetailPanel.vue
> +                data-cy="force-save-checkbox"
no need ?

2023-03-15 14:47 UTC, k-y0u commented on src/components/menu/FileExplorerActionMenu.vue
> +    data-cy="file-explorer-menu"
keep `-action`

2023-03-15 14:47 UTC, k-y0u commented on src/components/menu/FileExplorerActionMenu.vue
> +          data-cy="create-folder"
`create-folder-action-item`

2023-03-15 14:47 UTC, k-y0u commented on src/components/menu/GitBranchActionMenu.vue
> +    <q-list data-cy="git-branch-action-menu">
Move this data-cy to q-menu

2023-03-15 14:47 UTC, k-y0u commented on src/components/menu/GitBranchExpandListMenu.vue
TODO: rename -> it's note a menu

2023-03-15 14:47 UTC, k-y0u commented on src/components/menu/GitBranchExpandListMenu.vue
> +    <q-item-section data-cy="menu-text">
`expand-list-message` or `expand-list-text`

2023-03-15 14:47 UTC, k-y0u commented on src/components/menu/GitBranchMenu.vue
> +            data-cy="git-status"
git-status-icon

2023-03-15 14:47 UTC, k-y0u commented on src/components/menu/GitBranchMenu.vue
> +            data-cy="git-status"
or `git-status-item` in q-item

2023-03-15 14:47 UTC, k-y0u commented on src/components/menu/GitBranchMenu.vue
>          <q-item-section>{{ $t('actions.git.status') }}</q-item-section>
divide

2023-03-15 14:47 UTC, k-y0u commented on src/components/menu/GitBranchMenu.vue
> +          data-cy="expand-local-branch-menu"
should be put directly in component

2023-03-15 14:47 UTC, k-y0u commented on src/components/menu/GitBranchMenu.vue
> +          data-cy="expand-remote-branch-menu"
should be put directly in component

2023-03-15 14:47 UTC, k-y0u commented on src/components/menu/ModelizerSettingsMenu.vue
> +    data-cy="project-settings-button"
`modelizer-settings-button` or rename file

2023-03-15 14:47 UTC, k-y0u commented on src/components/menu/ModelizerSettingsMenu.vue
> +            :data-cy="`menu_${menuItem.key}`"
item_...

2023-03-15 14:47 UTC, k-y0u commented on src/components/ModelizerTextView.vue
> +        data-cy="filter-files-checkbox"
no need

2023-03-15 14:47 UTC, k-y0u commented on src/components/ModelizerModelView.vue
> +          data-cy="draw-area"
draw-container (div -> container ?)

2023-03-16 15:14 UTC, justinehell commented on cypress/e2e/HomePage/delete.project.feature
>      Then I expect current url is "modelizer/projectName/model"
done

2023-03-16 15:39 UTC, justinehell commented on src/components/form/GitAddRemoteForm.vue
> +      data-cy="repository-input"
done

2023-03-16 16:02 UTC, Zorin95670 commented on src/components/form/CreateFileForm.vue
> +      data-cy="name-input"
keep name-input

2023-03-17 09:08 UTC, k-y0u commented on cypress/e2e/HomePage/create.project.feature
> +    And  I visit the "/"
missing quote correction (note to myself)

2023-03-17 09:23 UTC, Zorin95670 approved these changes

2023-03-17 10:01 UTC, k-y0u approved these changes

2023-03-17 10:15 UTC, merged