Fix model selection
ditrit/leto-modelizer pull request #234
Opened 2023-04-27 10:07 UTC by k-y0u

2023-04-28 12:03 UTC, justinehell requested changes

2023-04-28 12:23 UTC, k-y0u commented on src/components/ModelizerTextView.vue
> +    return undefined;
to be consistent with `models.find()` l.80

Correcting the description should be enough, no ?

2023-04-28 12:25 UTC, k-y0u commented on cypress/e2e/ModelizerPage/TextView/file/switch.model.file.feature
> +    # Go to text view and check folders
not only...

2023-05-02 09:09 UTC, justinehell approved these changes

2023-05-02 09:41 UTC, merged