Improvement: about page
ditrit/leto-modelizer pull request #260
Opened 2023-05-16 12:27 UTC by Rahzbob

2023-05-16 13:47 UTC, Zorin95670 submitted a review, later dismissed

2023-05-16 15:05 UTC, justinehell requested changes

2023-05-16 15:05 UTC, justinehell commented on src/assets/about.json
> +      "avatar": "https://avatars.githubusercontent.com/u/105789397",
Change `avatars2` -> `avatars` everywhere ? @Zorin95670

2023-05-17 08:17 UTC, Rahzbob commented on src/assets/about.json
> +      "avatar": "https://avatars.githubusercontent.com/u/105789397",
done

2023-05-17 08:56 UTC, justinehell approved these changes

2023-05-31 09:40 UTC, Zorin95670 approved these changes

2023-06-06 14:02 UTC, closed without merging