Feature: Add project expansion item
ditrit/leto-modelizer pull request #267
Opened 2023-05-24 14:10 UTC by justinehell

Resolve #251

2023-05-25 09:41 UTC, Zorin95670 commented on changelog.md
> +  * Display left drawer
```
* Display a left drawer that contains:
  * A button to display recents projects
  * A short project list access
```

2023-05-25 10:33 UTC, justinehell commented on changelog.md
> +  * Display left drawer
done

2023-05-25 12:06 UTC, Zorin95670 submitted a review, later dismissed

2023-05-25 13:00 UTC, k-y0u requested changes

2023-05-25 13:00 UTC, k-y0u commented on changelog.md
> +    * A short project list access.
`project list` here, `projects list` in e2e tests... choose one

2023-05-25 13:11 UTC, justinehell commented on src/components/list/ShortProjectList.vue
> + * Initialize project list with the first four projects in alphabetical order.
done

2023-05-25 14:43 UTC, justinehell commented on src/components/list/ShortProjectList.vue
> +  <q-list class="short-project-list">
updated

2023-05-26 09:28 UTC, Zorin95670 submitted a review, later dismissed

2023-05-26 12:52 UTC, Zorin95670 approved these changes

2023-05-26 12:52 UTC, merged