Add margin bottom for button in ProjectCard
ditrit/leto-modelizer pull request #273
Opened 2023-05-31 13:23 UTC by Zorin95670

2023-05-31 13:42 UTC, k-y0u submitted a review, later dismissed

2023-05-31 13:42 UTC, justinehell submitted a review, later dismissed

2023-06-01 08:11 UTC, justinehell requested changes

2023-06-01 08:11 UTC, justinehell commented on cypress/e2e/HomePage/delete.project.feature
> +    And I expect '[data-cy="project-expansion-item"] [data-cy="item_projectName"]' exists
align `I`

2023-06-01 08:15 UTC, justinehell approved these changes

2023-06-01 09:54 UTC, k-y0u approved these changes

2023-06-01 12:01 UTC, merged