Feature: Redesign diagram list
ditrit/leto-modelizer pull request #290
Opened 2023-06-09 11:40 UTC by justinehell

Resolve #278

2023-06-09 14:10 UTC, Zorin95670 requested changes

2023-06-09 14:10 UTC, Zorin95670 commented on src/components/grid/DiagramGrid.vue
> +    class="row text-center text-h6 text-grey empty-grid"
missing class name `diagram-grid`

2023-06-09 14:10 UTC, Zorin95670 commented on src/components/table/DiagramTable.vue
> +  <q-table
missing class name `diagram-table`

2023-06-09 14:17 UTC, justinehell commented on src/components/grid/DiagramGrid.vue
> +    class="row text-center text-h6 text-grey empty-grid"
done

2023-06-09 14:17 UTC, justinehell commented on src/components/table/DiagramTable.vue
> +  <q-table
done

2023-06-09 14:35 UTC, Zorin95670 approved these changes

2023-06-12 09:42 UTC, k-y0u requested changes

2023-06-12 09:42 UTC, k-y0u commented on tests/unit/components/ModelsView.spec.js
> +      wrapper.vm.onDiagramClick(model);
model -> diagram

2023-06-12 09:46 UTC, justinehell commented on src/composables/PluginManager.js
> + * @return {Object} Return a plugin.
done

2023-06-12 09:46 UTC, justinehell commented on src/composables/PluginManager.js
> + * @return {Object} Return an array of plugin.
done

2023-06-12 09:47 UTC, justinehell commented on src/composables/Project.js
> +      return isDir ? {
done

2023-06-12 09:49 UTC, justinehell commented on tests/unit/components/ModelsView.spec.js
> +      wrapper.vm.onDiagramClick(model);
done

2023-06-12 14:33 UTC, k-y0u submitted a review, later dismissed

2023-06-13 08:22 UTC, Zorin95670 submitted a review, later dismissed

2023-06-13 08:23 UTC, k-y0u submitted a review, later dismissed

2023-06-13 09:33 UTC, k-y0u approved these changes

2023-06-13 09:33 UTC, Zorin95670 approved these changes

2023-06-13 09:59 UTC, merged