Refacto layouts
ditrit/leto-modelizer pull request #328
Opened 2023-06-29 09:21 UTC by k-y0u

resolves #296

2023-07-04 15:43 UTC, justinehell requested changes

2023-07-04 15:43 UTC, justinehell commented on src/components/drawer/ModelizerTextLeftDrawer.vue
> +    data-cy="home-drawer"
why not same name as component ?

2023-07-05 08:12 UTC, Zorin95670 requested changes

2023-07-05 08:18 UTC, justinehell requested changes

2023-07-05 09:44 UTC, k-y0u commented on src/components/drawer/ModelizerTextLeftDrawer.vue
> +    data-cy="home-drawer"
done

2023-07-05 09:44 UTC, k-y0u commented on src/components/drawer/ModelizerTextLeftDrawer.vue
> +  <default-drawer
done

2023-07-05 09:44 UTC, k-y0u commented on src/pages/ModelizerDrawPage.vue
> -  div#root svg {
done

2023-07-05 09:44 UTC, k-y0u commented on src/pages/ModelizerDrawPage.vue
> -<style scoped>
done

2023-07-05 09:44 UTC, k-y0u commented on src/pages/ModelizerDrawPage.vue
> -  #viewport {
done

2023-07-05 09:45 UTC, k-y0u commented on src/layouts/ModelizerDrawLayout.vue
> +  const pluginName = query.value.path.split('/')[0];
done

2023-07-05 15:15 UTC, justinehell approved these changes

2023-07-06 08:46 UTC, Zorin95670 approved these changes

2023-07-06 08:46 UTC, merged