Feature: Create variables panel
ditrit/leto-modelizer pull request #343
Opened 2023-07-19 15:53 UTC by justinehell

Resolve #304

2023-07-20 08:16 UTC, k-y0u requested changes

2023-07-20 08:16 UTC, k-y0u commented on tests/unit/components/list/VariableList.spec.js
> +      it('should match "variables"', () => {
doesn't match "variables" but an array containing 2 Variable.

2023-07-20 08:16 UTC, k-y0u commented on tests/unit/components/list/VariableList.spec.js
> +    it('transforms variables into the desired formatted object', () => {
should transform

2023-07-20 08:16 UTC, k-y0u commented on tests/unit/components/list/VariableList.spec.js
> +      it('should be a list of Object with "name", "label" and "field" as keys and corresponding data as values', () => {
list of objects

2023-07-20 08:16 UTC, k-y0u commented on cypress/e2e/ModelizerPage/DrawView/plugin/DisplayComponentVariables.feature
> +  Scenario: Add variables inside component parsable files should display it on the variables tab inside Modelizer draw left drawer
modelizer draw (like L.1)

2023-07-20 08:16 UTC, k-y0u commented on cypress/e2e/ModelizerPage/DrawView/plugin/DisplayComponentVariables.feature
> +    And  I wait 2 seconds
better use an `expect` on `[data-cy="draw-page-variables-tab"]` if possible

2023-07-20 08:16 UTC, k-y0u commented on changelog.md
> +  * Display variables panel.
Add variables panel in left drawer.

2023-07-20 08:20 UTC, justinehell commented on src/components/list/VariableList.vue
> + * Transforms the input variables into the desired formatted object.
done

2023-07-20 08:21 UTC, justinehell commented on src/components/list/VariableList.vue
> +    const { path } = variable;
linter says break lines, done

2023-07-20 08:22 UTC, justinehell commented on src/components/list/VariableList.vue
> +onMounted(async () => {
yep, forgot to remove it. Done

2023-07-20 08:24 UTC, justinehell commented on tests/unit/components/list/VariableList.spec.js
> +    it('transforms variables into the desired formatted object', () => {
done

2023-07-20 08:24 UTC, justinehell commented on tests/unit/components/list/VariableList.spec.js
> +      it('should be a list of Object with "name", "label" and "field" as keys and corresponding data as values', () => {
done

2023-07-20 08:25 UTC, justinehell commented on changelog.md
> +  * Display variables panel.
done

2023-07-20 08:25 UTC, justinehell commented on cypress/e2e/ModelizerPage/DrawView/plugin/DisplayComponentVariables.feature
> +  Scenario: Add variables inside component parsable files should display it on the variables tab inside Modelizer draw left drawer
done

2023-07-20 09:00 UTC, justinehell commented on cypress/e2e/ModelizerPage/DrawView/plugin/DisplayComponentVariables.feature
> +    And  I wait 2 seconds
changed

2023-07-20 09:01 UTC, justinehell commented on tests/unit/components/list/VariableList.spec.js
> +      it('should match "variables"', () => {
done

2023-07-20 12:24 UTC, Zorin95670 requested changes

2023-07-20 12:24 UTC, Zorin95670 commented on src/components/list/VariableList.vue
> +    formattedVariables[path][category].push({ name, value });
why don't push directly variable ?

2023-07-20 13:15 UTC, justinehell commented on src/components/list/VariableList.vue
> +    formattedVariables[path][category].push({ name, value });
done

2023-07-24 09:04 UTC, k-y0u submitted a review, later dismissed

2023-07-24 12:58 UTC, k-y0u approved these changes

2023-07-24 13:07 UTC, Zorin95670 approved these changes

2023-07-24 13:07 UTC, merged