Improvement/file test coverage
ditrit/leto-modelizer pull request #416
Opened 2023-09-29 07:22 UTC by justinehell

Add coverage for `ModelizerDrawPage.vue` file

2023-09-29 13:53 UTC, k-y0u requested changes

2023-09-29 13:53 UTC, k-y0u commented on tests/unit/pages/ModelizerDrawPage.spec.js
> +      await wrapper.vm.onDefaultEvent(param);
Jump

2023-09-29 13:53 UTC, k-y0u commented on tests/unit/pages/ModelizerDrawPage.spec.js
> +    });
Jump after

2023-09-29 13:53 UTC, k-y0u commented on tests/unit/pages/ModelizerDrawPage.spec.js
> +      await wrapper.vm.onDefaultEvent(param);
jump before

2023-09-29 13:53 UTC, k-y0u commented on tests/unit/pages/ModelizerDrawPage.spec.js
> +    it('should call renderModel if event.action is either "update", "delete", or "add"', async () => {
remove coma after "delete"

2023-09-29 13:53 UTC, k-y0u commented on tests/unit/pages/ModelizerDrawPage.spec.js
> +      await wrapper.vm.dropHandler(param);
jump

2023-09-29 13:53 UTC, k-y0u commented on tests/unit/pages/ModelizerDrawPage.spec.js
> +      await wrapper.vm.dropHandler(param);
jump

2023-09-29 13:53 UTC, k-y0u commented on tests/unit/pages/ModelizerDrawPage.spec.js
> +      await wrapper.vm.dropHandler(param);
jump

2023-09-29 13:57 UTC, justinehell commented on tests/unit/pages/ModelizerDrawPage.spec.js
> +      await wrapper.vm.onDefaultEvent(param);
done

2023-09-29 13:57 UTC, justinehell commented on tests/unit/pages/ModelizerDrawPage.spec.js
> +    });
done

2023-09-29 13:59 UTC, justinehell commented on tests/unit/pages/ModelizerDrawPage.spec.js
> +    it('should call renderModel if event.action is either "update", "delete", or "add"', async () => {
done

2023-09-29 14:00 UTC, justinehell commented on tests/unit/pages/ModelizerDrawPage.spec.js
> +      await wrapper.vm.dropHandler(param);
done

2023-09-29 14:00 UTC, justinehell commented on tests/unit/pages/ModelizerDrawPage.spec.js
> +      await wrapper.vm.dropHandler(param);
done

2023-09-29 14:07 UTC, k-y0u approved these changes

2023-10-02 07:38 UTC, aboubakar14 approved these changes

2023-10-02 08:05 UTC, merged