Bugfix/plugins single file diagram
ditrit/leto-modelizer pull request #418
Opened 2023-10-02 10:02 UTC by justinehell

Resolve https://github.com/ditrit/leto-modelizer/issues/407

2023-10-02 15:00 UTC, k-y0u requested changes

2023-10-02 15:06 UTC, justinehell commented on src/composables/Project.js
> +      .map((file) => new FileInformation({ path: `${filePath}${file}` })));
done

2023-10-03 07:42 UTC, k-y0u approved these changes

2023-10-03 07:45 UTC, aboubakar14 approved these changes

2023-10-03 08:18 UTC, merged