Feature: Integrate CF create project from template
ditrit/leto-modelizer pull request #448
Opened 2023-11-15 10:43 UTC by aboubakar14

2023-11-15 13:22 UTC, justinehell requested changes

2023-11-15 13:22 UTC, justinehell commented on src/components/grid/TemplateGrid.vue
> +        data-cy="template-project-grid-unauthorized"
need to change related e2e tests

2023-11-15 13:29 UTC, justinehell submitted a review, later dismissed

2023-11-15 14:14 UTC, justinehell approved these changes

2023-11-15 14:18 UTC, Zorin95670 approved these changes

2023-11-15 15:18 UTC, Zorin95670 approved these changes

2023-11-15 15:19 UTC, justinehell approved these changes

2023-11-17 10:38 UTC, Zorin95670 approved these changes

2023-11-17 10:38 UTC, merged