Add ellipsis on file name container in file explorer
ditrit/leto-modelizer pull request #462
Opened 2023-11-30 08:54 UTC by k-y0u

fixes #383

2023-11-30 09:59 UTC, justinehell requested changes

2023-11-30 09:59 UTC, justinehell commented on src/components/FileExplorer.vue
> +        <div class="file-name-container">
maybe add `:title="node.label"` to have the complete name on hover?

2023-11-30 10:18 UTC, justinehell submitted a review, later dismissed

2023-11-30 10:21 UTC, aboubakar14 submitted a review, later dismissed

2023-12-01 09:01 UTC, Zorin95670 approved these changes

2023-12-01 09:02 UTC, merged