Feature: integrate cli
ditrit/leto-modelizer pull request #59
Opened 2022-09-02 14:44 UTC by Zorin95670

2022-09-19 10:07 UTC, k-y0u requested changes

2022-09-19 10:07 UTC, k-y0u commented on CONTRIBUTING.md
> +Run eslint fix on the project.
to fix

2022-09-19 10:07 UTC, k-y0u commented on README.md
> +- Implements you own plugin
your own

2022-09-19 10:07 UTC, k-y0u commented on README.md
enterprise -> company (c'est pas star trek ici !)

2022-09-19 10:07 UTC, k-y0u commented on README.md
> +When you install all your wanted plugin, please run this commands `npm run plugin:init` to finalise all plugins installation.
all your wanted pluginS

2022-09-19 10:07 UTC, k-y0u commented on README.md
> +For now, we don't have much plugin to propose to you, but follow us and in next month you will see new plugins like (Jenkins or Kubernetes).
`like` should be in the parentheses.

2022-09-20 09:20 UTC, Zorin95670 commented on CONTRIBUTING.md
> +Run eslint check on the project.
done

2022-09-20 09:20 UTC, Zorin95670 commented on CONTRIBUTING.md
> +Run eslint fix on the project.
done

2022-09-20 09:22 UTC, Zorin95670 commented on README.md
> +- Implements you own plugin
done

2022-09-20 09:22 UTC, Zorin95670 commented on README.md
done

2022-09-20 09:24 UTC, Zorin95670 commented on README.md
> +When you install all your wanted plugin, please run this commands `npm run plugin:init` to finalise all plugins installation.
done

2022-09-20 12:07 UTC, k-y0u requested changes

2022-09-20 12:07 UTC, k-y0u commented on README.md
> +Once you have to install and initialize all yours plugins, run this commands to build the app:
Once you have to install -> Once you have install

2022-09-20 12:07 UTC, k-y0u commented on README.md
> +For now, we don't have much plugin to propose to you, but follow us and in next month you will see new plugins (like Jenkins or Kubernetes).
in THE next (few) monthS

2022-09-20 12:22 UTC, k-y0u approved these changes

2022-09-20 12:36 UTC, merged